### PR TITLE
Dev 0.1

### PR DESCRIPTION
**Pull request by generationmake**
generate prototype

### CODE REVIEW

**Comment by generationmake** [comment]
@aentinger 
please check this design

**Comment by aentinger** [comment]
Looks good to me :+1: , thank you for the effort :bow: .

* Please add M3 mounting holes
* I had been thinking of **right angle and vertical** PP connectors (see [datasheet](https://www.andersonpower.com/content/dam/app/ecommerce/product-pdfs/pp/ds-pp1545.pdf) at the bottom of the second page). I believe it allows a neater installation of the connected cables, as compared to only vertical plugin where it looks like an electric rat's nest.

**Comment by aentinger** [comment]
Ping @generationmake 😁

**Comment by aentinger** [comment]
anderson-angled

**Comment by generationmake** [comment]
@aentinger 
I changed to horizontal power poles.
correct pin order numbers are: 1377G11 and 1377G12
please check again.

**Comment by aentinger** [comment]
Looks good to me :+1: An order for parts has been sent, shipping to your address.

**Comment by generationmake** [comment]
@aentinger 
please check again

**Comment by aentinger** [comment]
LGTM 👍 . Although the 3D render looks a bit crazy with both mounting options displayed on top of one another.

**Comment by generationmake** [comment]
Unfortunately KiCAD at this stage does not really support BOM options. I will fix this with the CAD data for the enclosure.
I will order this PCB and then we will see.

**Comment by aentinger** [comment]
>Unfortunately KiCAD at this stage does not really support BOM options.

:+1: 

Also - what about the option for adding another distributor via side-ways facing connectors, as you've mentioned yesterday during our call?

**Comment by generationmake** [comment]
prototype works as expected.
IMG_20230414_175949
IMG_20230414_180009

**Comment by aentinger** [comment]
Terrific! Looks fantastic! Great job!

**Pull request merged**
