### PR TITLE
Enclosure

### PR DESCRIPTION
**Pull request by generationmake**
enclosure for 90 degree power poles.

### CODE REVIEW

**Comment by generationmake** [comment]
@aentinger 
please check the enclosure

**Comment by aentinger** [comment]
Well, it contains many delicate forms. I'll commence with a test print and we'll see about the out-come.

**Review by aentinger — APPROVED** [review]
LGTM 👍 

IMG_20230411_054743_769
IMG_20230411_054730_898

**Comment by generationmake** [comment]
very nice!
PCB should arrive on friday

**Pull request merged**
